### ISSUE TITLE
scala/doobie-sqlite

### ISSUE THREAD

**Issue by seoh** [seoh/minimal-boilerplate#1]
# TODO
- [ ] add test for IO
- [ ] add test for queries
- [ ] separate from CMD and DB
  - [ ] inject DB service to CMD

# why
- [ ] SIGINT is not captured on Shutdown Hook?
- [ ] multiline query wihtout `|` not accepted?
  - [ ] is an issue for sqlite or doobie?
